import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { useState, useEffect } from 'react';
import { HomeCard } from '../components/cards';
import TextTransition, { presets } from "react-text-transition";

export default function Home() {
  const designerTextArray = [
    "UI/UX",
    "Graphic",
    "Product"
  ];

  const [index, setIndex] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setIndex(index => index + 1)
    }, 1500);
    return () => {
      clearTimeout(timer);
    };
  }, []);

  const text = index ? designerTextArray[index % designerTextArray.length] : '';

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          👋 Hi! I'm Rohit Nag.
        </h1>

        <div className={styles.description}>
          I'm a Mechanical Engineering student <a href="">@Imperial</a>  with an interest in embedded systems, physics modelling and AI.
          <br />
          Also a questionable &nbsp;
          <TextTransition inline springConfig={presets.wobbly}>
            {text}
          </TextTransition>
          &nbsp; designer on the side 😁.
        </div>

        <div className={styles.grid}>
          <HomeCard
            link=""
            title="Projects"
            description="Explore some of university and side projects." />

          <HomeCard
            link=""
            title="Art"
            description="View my recent art pieces." />

          <HomeCard
            link=""
            title="Graphics"
            description="View some of the posters and logos I've made." />

          <HomeCard
            link=""
            title="About"
            description="Learn about my background and experiences." />
        </div>
      </main>

      <footer className={styles.footer}>
        © 2022 Rohit Nag
      </footer>
    </div>
  )
}
